import type { Metadata } from "next";
import { Laila } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
// import { ReactLenis } from "@/lib/lenis";
import Web3ModalProvider from "@/context";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import { AOSInit } from "@/components/aos";

const laila = Laila({ subsets: ["latin"], weight: ["300", "400", "500", "600", "700"] });

const detacher = localFont({
  src: "./fonts/detacher.otf",
  variable: "--font-detacher",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AOSInit />
      <body className={cn("bg-black", "text-white", laila.className, detacher.variable, "antialiased")}>
        <Web3ModalProvider>
          <Navbar />
          {children}
        </Web3ModalProvider>
      </body>
      <Toaster richColors />
    </html>
  );
}
